# Generated by Django 3.1.5 on 2021-02-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePartida', models.CharField(max_length=5000)),
                ('Unidad', models.CharField(max_length=25)),
                ('DesPartida', models.CharField(max_length=5000)),
                ('FormaMedicion', models.CharField(max_length=5000)),
                ('MetodoPago', models.CharField(max_length=5000)),
            ],
        ),
    ]
